# Login Page Elements
txt_loginUserName = "name:userName"
txt_loginPassword = "name:password"
btn_signIn = "name:submit"

# Register Page Elements
link_Reg = "link:REGISTER"
txt_firstName = "name:firstName"
txt_lastName = "name:lastName"
txt_phone = "name:phone"
txt_email = "name:userName"
txt_address = "name:address1"
txt_city = "name:city"
txt_state = "name:state"
txt_postCode = "name:postalCode"
drp_country = "name:country"
txt_userName = "name:email"
txt_password = "name:password"
txt_confirmedPassword = "name:confirmPassword"
btn_submit = "name:submit"
